### ISSUE TITLE
Improve This unable to improve buildings without <stuffCategories>

### ISSUE THREAD

**Issue by TheOldOne822** [Hexicube/RimWorld-Mods#1]
Any non Stuffed building with Quality is unable to be Improved. trying to causes the builder to try then go into "standing" than try to improve again.
Vanilla Expanded has a lot of such buildings in it plus Android Tiers android only hospital bed is effected too and if used with Everything Has Quality a large portion of the buildings are effected.

**Comment by Hexicube** [comment]
Possibly fixed, I'll need logs if not.

If the error is "Cannot get AdjustedCostList for <thing> with null Stuff.", the mod hasn't updated.

**Comment by TheOldOne822** [comment]
It now works
